// generated file - DO NOT EDIT
//
let tzLookup = [
{abbr:"ACDT",offset:"+10:30",name:"Australian Central Daylight Savings Time "},
{abbr:"ACST",offset:"+09:30",name:"Australian Central Standard Time "},
{abbr:"ACWST",offset:"+08:45",name:"Australian Central Western Standard Time (unofficial) "},
{abbr:"ADT",offset:"-03:00",name:"Atlantic Daylight Time "},
{abbr:"AEDT",offset:"+11:00",name:"Australian Eastern Daylight Savings Time "},
{abbr:"AEST",offset:"+10:00",name:"Australian Eastern Standard Time "},
{abbr:"AFT",offset:"+04:30",name:"Afghanistan Time "},
{abbr:"AKDT",offset:"-08:00",name:"Alaska Daylight Time "},
{abbr:"AKST",offset:"-09:00",name:"Alaska Standard Time "},
{abbr:"ALMT",offset:"+06:00",name:"Alma-Ata Time "},
{abbr:"AMST",offset:"-03:00",name:"Amazon Summer Time (Brazil) "},
{abbr:"AMT",offset:"-04:00",name:"Amazon Time (Brazil) "},
{abbr:"ANAT",offset:"+12:00",name:"Anadyr Time "},
{abbr:"AQTT",offset:"+05:00",name:"Aqtobe Time "},
{abbr:"ART",offset:"-03:00",name:"Argentina Time "},
{abbr:"AST",offset:"+03:00",name:"Arabia Standard Time "},
{abbr:"AWST",offset:"+08:00",name:"Australian Western Standard Time "},
{abbr:"AZOST",offset:"+00:00",name:"Azores Summer Time "},
{abbr:"AZOT",offset:"-01:00",name:"Azores Standard Time "},
{abbr:"AZT",offset:"+04:00",name:"Azerbaijan Time "},
{abbr:"BDT",offset:"+08:00",name:"Brunei Time "},
{abbr:"BIOT",offset:"+06:00",name:"British Indian Ocean Time "},
{abbr:"BIT",offset:"-12:00",name:"Baker Island Time "},
{abbr:"BOT",offset:"-04:00",name:"Bolivia Time "},
{abbr:"BRST",offset:"-02:00",name:"Brasilia Summer Time "},
{abbr:"BRT",offset:"-03:00",name:"Brasilia Time "},
{abbr:"BST",offset:"+06:00",name:"Bangladesh Standard Time "},
{abbr:"BTT",offset:"+06:00",name:"Bhutan Time "},
{abbr:"CAT",offset:"+02:00",name:"Central Africa Time "},
{abbr:"CCT",offset:"+06:30",name:"Cocos Islands Time "},
{abbr:"CDT",offset:"-05:00",name:"Central Daylight Time (North America) "},
{abbr:"CEST",offset:"+02:00",name:"Central European Summer Time (Cf. HAEC) "},
{abbr:"CET",offset:"+01:00",name:"Central European Time "},
{abbr:"CHADT",offset:"+13:45",name:"Chatham Daylight Time "},
{abbr:"CHAST",offset:"+12:45",name:"Chatham Standard Time "},
{abbr:"CHOT",offset:"+08:00",name:"Choibalsan Standard Time "},
{abbr:"CHOST",offset:"+09:00",name:"Choibalsan Summer Time "},
{abbr:"CHST",offset:"+10:00",name:"Chamorro Standard Time "},
{abbr:"CHUT",offset:"+10:00",name:"Chuuk Time "},
{abbr:"CIST",offset:"-08:00",name:"Clipperton Island Standard Time "},
{abbr:"CIT",offset:"+08:00",name:"Central Indonesia Time "},
{abbr:"CKT",offset:"-10:00",name:"Cook Island Time "},
{abbr:"CLST",offset:"-03:00",name:"Chile Summer Time "},
{abbr:"CLT",offset:"-04:00",name:"Chile Standard Time "},
{abbr:"COST",offset:"-04:00",name:"Colombia Summer Time "},
{abbr:"COT",offset:"-05:00",name:"Colombia Time "},
{abbr:"CST",offset:"-06:00",name:"Central Standard Time (North America) "},
{abbr:"CT",offset:"+08:00",name:"China Time "},
{abbr:"CVT",offset:"-01:00",name:"Cape Verde Time "},
{abbr:"CWST",offset:"+08:45",name:"Central Western Standard Time (Australia) unofficial "},
{abbr:"CXT",offset:"+07:00",name:"Christmas Island Time "},
{abbr:"DAVT",offset:"+07:00",name:"Davis Time "},
{abbr:"DDUT",offset:"+10:00",name:"Dumont d'Urville Time "},
{abbr:"DFT",offset:"+01:00",name:"AIX-specific equivalent of Central European Time "},
{abbr:"EASST",offset:"-05:00",name:"Easter Island Summer Time "},
{abbr:"EAST",offset:"-06:00",name:"Easter Island Standard Time "},
{abbr:"EAT",offset:"+03:00",name:"East Africa Time "},
{abbr:"ECT",offset:"-05:00",name:"Ecuador Time "},
{abbr:"EDT",offset:"-04:00",name:"Eastern Daylight Time (North America) "},
{abbr:"EEST",offset:"+03:00",name:"Eastern European Summer Time "},
{abbr:"EET",offset:"+02:00",name:"Eastern European Time "},
{abbr:"EGST",offset:"+00:00",name:"Eastern Greenland Summer Time "},
{abbr:"EGT",offset:"-01:00",name:"Eastern Greenland Time "},
{abbr:"EIT",offset:"+09:00",name:"Eastern Indonesian Time "},
{abbr:"EST",offset:"-05:00",name:"Eastern Standard Time (North America) "},
{abbr:"FET",offset:"+03:00",name:"Further-eastern European Time "},
{abbr:"FJT",offset:"+12:00",name:"Fiji Time "},
{abbr:"FKST",offset:"-03:00",name:"Falkland Islands Summer Time "},
{abbr:"FKT",offset:"-04:00",name:"Falkland Islands Time "},
{abbr:"FNT",offset:"-02:00",name:"Fernando de Noronha Time "},
{abbr:"GALT",offset:"-06:00",name:"Galapagos Time "},
{abbr:"GAMT",offset:"-09:00",name:"Gambier Islands Time "},
{abbr:"GET",offset:"+04:00",name:"Georgia Standard Time "},
{abbr:"GFT",offset:"-03:00",name:"French Guiana Time "},
{abbr:"GILT",offset:"+12:00",name:"Gilbert Island Time "},
{abbr:"GIT",offset:"-09:00",name:"Gambier Island Time "},
{abbr:"GMT",offset:"+00:00",name:"Greenwich Mean Time "},
{abbr:"GST",offset:"+04:00",name:"Gulf Standard Time "},
{abbr:"GYT",offset:"-04:00",name:"Guyana Time "},
{abbr:"HDT",offset:"-09:00",name:"Hawaii-Aleutian Daylight Time "},
{abbr:"HAEC",offset:"+02:00",name:"Heure Avancee d'Europe Centrale French-language name for CEST "},
{abbr:"HST",offset:"-10:00",name:"Hawaii-Aleutian Standard Time "},
{abbr:"HKT",offset:"+08:00",name:"Hong Kong Time "},
{abbr:"HMT",offset:"+05:00",name:"Heard and McDonald Islands Time "},
{abbr:"HOVST",offset:"+08:00",name:"Hovd Summer Time (not used from 2017-present) "},
{abbr:"HOVT",offset:"+07:00",name:"Hovd Time "},
{abbr:"ICT",offset:"+07:00",name:"Indochina Time "},
{abbr:"IDLW",offset:"-12:00",name:"International Day Line West time zone "},
{abbr:"IDT",offset:"+03:00",name:"Israel Daylight Time "},
{abbr:"IOT",offset:"+03:00",name:"Indian Ocean Time "},
{abbr:"IRDT",offset:"+04:30",name:"Iran Daylight Time "},
{abbr:"IRKT",offset:"+08:00",name:"Irkutsk Time "},
{abbr:"IRST",offset:"+03:30",name:"Iran Standard Time "},
{abbr:"IST",offset:"+05:30",name:"Indian Standard Time "},
{abbr:"JST",offset:"+09:00",name:"Japan Standard Time "},
{abbr:"KALT",offset:"+02:00",name:"Kaliningrad Time "},
{abbr:"KGT",offset:"+06:00",name:"Kyrgyzstan Time "},
{abbr:"KOST",offset:"+11:00",name:"Kosrae Time "},
{abbr:"KRAT",offset:"+07:00",name:"Krasnoyarsk Time "},
{abbr:"KST",offset:"+09:00",name:"Korea Standard Time "},
{abbr:"LHST",offset:"+10:30",name:"Lord Howe Standard Time "},
{abbr:"LINT",offset:"+14:00",name:"Line Islands Time "},
{abbr:"MAGT",offset:"+12:00",name:"Magadan Time "},
{abbr:"MART",offset:"-09:30",name:"Marquesas Islands Time "},
{abbr:"MAWT",offset:"+05:00",name:"Mawson Station Time "},
{abbr:"MDT",offset:"-06:00",name:"Mountain Daylight Time (North America) "},
{abbr:"MET",offset:"+01:00",name:"Middle European Time Same zone as CET "},
{abbr:"MEST",offset:"+02:00",name:"Middle European Summer Time Same zone as CEST "},
{abbr:"MHT",offset:"+12:00",name:"Marshall Islands Time "},
{abbr:"MIST",offset:"+11:00",name:"Macquarie Island Station Time "},
{abbr:"MIT",offset:"-09:30",name:"Marquesas Islands Time "},
{abbr:"MMT",offset:"+06:30",name:"Myanmar Standard Time "},
{abbr:"MSK",offset:"+03:00",name:"Moscow Time "},
{abbr:"MST",offset:"-07:00",name:"Mountain Standard Time (North America) "},
{abbr:"MUT",offset:"+04:00",name:"Mauritius Time "},
{abbr:"MVT",offset:"+05:00",name:"Maldives Time "},
{abbr:"MYT",offset:"+08:00",name:"Malaysia Time "},
{abbr:"NCT",offset:"+11:00",name:"New Caledonia Time "},
{abbr:"NDT",offset:"-02:30",name:"Newfoundland Daylight Time "},
{abbr:"NFT",offset:"+11:00",name:"Norfolk Island Time "},
{abbr:"NOVT",offset:"+07:00",name:"Novosibirsk Time "},
{abbr:"NPT",offset:"+05:45",name:"Nepal Time "},
{abbr:"NST",offset:"-03:30",name:"Newfoundland Standard Time "},
{abbr:"NT",offset:"-03:30",name:"Newfoundland Time "},
{abbr:"NUT",offset:"-11:00",name:"Niue Time "},
{abbr:"NZDT",offset:"+13:00",name:"New Zealand Daylight Time "},
{abbr:"NZST",offset:"+12:00",name:"New Zealand Standard Time "},
{abbr:"OMST",offset:"+06:00",name:"Omsk Time "},
{abbr:"ORAT",offset:"+05:00",name:"Oral Time "},
{abbr:"PDT",offset:"-07:00",name:"Pacific Daylight Time (North America) "},
{abbr:"PET",offset:"-05:00",name:"Peru Time "},
{abbr:"PETT",offset:"+12:00",name:"Kamchatka Time "},
{abbr:"PGT",offset:"+10:00",name:"Papua New Guinea Time "},
{abbr:"PHOT",offset:"+13:00",name:"Phoenix Island Time "},
{abbr:"PHT",offset:"+08:00",name:"Philippine Time "},
{abbr:"PKT",offset:"+05:00",name:"Pakistan Standard Time "},
{abbr:"PMDT",offset:"-02:00",name:"Saint Pierre and Miquelon Daylight Time "},
{abbr:"PMST",offset:"-03:00",name:"Saint Pierre and Miquelon Standard Time "},
{abbr:"PONT",offset:"+11:00",name:"Pohnpei Standard Time "},
{abbr:"PST",offset:"-08:00",name:"Pacific Standard Time (North America) "},
{abbr:"PYST",offset:"-03:00",name:"Paraguay Summer Time "},
{abbr:"PYT",offset:"-04:00",name:"Paraguay Time "},
{abbr:"RET",offset:"+04:00",name:"Reunion Time "},
{abbr:"ROTT",offset:"-03:00",name:"Rothera Research Station Time "},
{abbr:"SAKT",offset:"+11:00",name:"Sakhalin Island Time "},
{abbr:"SAMT",offset:"+04:00",name:"Samara Time "},
{abbr:"SAST",offset:"+02:00",name:"South African Standard Time "},
{abbr:"SBT",offset:"+11:00",name:"Solomon Islands Time "},
{abbr:"SCT",offset:"+04:00",name:"Seychelles Time "},
{abbr:"SDT",offset:"-10:00",name:"Samoa Daylight Time "},
{abbr:"SGT",offset:"+08:00",name:"Singapore Time "},
{abbr:"SLST",offset:"+05:30",name:"Sri Lanka Standard Time "},
{abbr:"SRET",offset:"+11:00",name:"Srednekolymsk Time "},
{abbr:"SRT",offset:"-03:00",name:"Suriname Time "},
{abbr:"SST",offset:"+08:00",name:"Singapore Standard Time "},
{abbr:"SYOT",offset:"+03:00",name:"Showa Station Time "},
{abbr:"TAHT",offset:"-10:00",name:"Tahiti Time "},
{abbr:"THA",offset:"+07:00",name:"Thailand Standard Time "},
{abbr:"TFT",offset:"+05:00",name:"French Southern and Antarctic Time "},
{abbr:"TJT",offset:"+05:00",name:"Tajikistan Time "},
{abbr:"TKT",offset:"+13:00",name:"Tokelau Time "},
{abbr:"TLT",offset:"+09:00",name:"Timor Leste Time "},
{abbr:"TMT",offset:"+05:00",name:"Turkmenistan Time "},
{abbr:"TRT",offset:"+03:00",name:"Turkey Time "},
{abbr:"TOT",offset:"+13:00",name:"Tonga Time "},
{abbr:"TVT",offset:"+12:00",name:"Tuvalu Time "},
{abbr:"ULAST",offset:"+09:00",name:"Ulaanbaatar Summer Time "},
{abbr:"ULAT",offset:"+08:00",name:"Ulaanbaatar Standard Time "},
{abbr:"UTC",offset:"+00:00",name:"Coordinated Universal Time "},
{abbr:"UYST",offset:"-02:00",name:"Uruguay Summer Time "},
{abbr:"UYT",offset:"-03:00",name:"Uruguay Standard Time "},
{abbr:"UZT",offset:"+05:00",name:"Uzbekistan Time "},
{abbr:"VET",offset:"-04:00",name:"Venezuelan Standard Time "},
{abbr:"VLAT",offset:"+10:00",name:"Vladivostok Time "},
{abbr:"VOLT",offset:"+04:00",name:"Volgograd Time "},
{abbr:"VOST",offset:"+06:00",name:"Vostok Station Time "},
{abbr:"VUT",offset:"+11:00",name:"Vanuatu Time "},
{abbr:"WAKT",offset:"+12:00",name:"Wake Island Time "},
{abbr:"WAST",offset:"+02:00",name:"West Africa Summer Time "},
{abbr:"WAT",offset:"+01:00",name:"West Africa Time "},
{abbr:"WEST",offset:"+01:00",name:"Western European Summer Time "},
{abbr:"WET",offset:"+00:00",name:"Western European Time "},
{abbr:"WIT",offset:"+07:00",name:"Western Indonesian Time "},
{abbr:"WST",offset:"+08:00",name:"Western Standard Time "},
{abbr:"YAKT",offset:"+09:00",name:"Yakutsk Time "},
];
